lint:
  actions_ci: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nf-dragen_logo_light.png
    - docs/images/nf-core-nf-dragen_logo_light.png
    - docs/images/nf-core-nf-dragen_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nf-dragen_logo_light.png
    - docs/images/nf-core-nf-dragen_logo_light.png
    - docs/images/nf-core-nf-dragen_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 2.14.1
repository_type: pipeline
template:
  author: "Harshil Patel, Graham Wright"
  description: nf-dragen is a simple, proof-of-concept Nextflow pipeline to run the Illumina DRAGEN licensed suite of tools.
  force: false
  is_nfcore: false
  name: nf-seqerakit
  org: seqeralabs
  outdir: .
  skip_features:
    - nf_core_configs
    - license
    - email
    - adaptivecard
    - slackreport
    - documentation
    - rocrate
  version: 0.1.0dev
